### ISSUE TITLE
Wich fan to use with the stealth max

### ISSUE THREAD

**Issue by Switch-Witch** [nevermore3d/StealthMax#2]
Hi,

wich fan could be used with the stealth max? I didn`t find any notice in the description.

**Comment by bartlammers** [comment]
Delta bfb0712hf, try to find one with a silver label.
They are sold on AliExpress and the likes, it's a round 65mm fan

**Comment by Switch-Witch** [comment]
Thank you - I`ll try to find a silver label

**Comment by KepleRPL** [comment]
What about Sanyo 9TD12P6G001 (70x20mm)?

**Comment by 0ndsk4** [comment]
Once everything works well with the delta, a sanyo variant is a simple cut and paste mod. But it’s a pain maintaining different versions at a stage where stuff still changes. 
The sanyo is a superior fan, but since the main point of stealthmax was to make everything simpler and cheaper, it made sense starting out with the fan that can be had in the 5-20$ range instead of 45-65$.
